version: '3.1'

services:

  dbserver:
    image: mysql:5
    ports:
      - 3306:3306
    hostname: dbserver
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: dbserver
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DHNnGJtf2sX3
      MYSQL_DATABASE: metabase_test
      MYSQL_USER: metabase_test
      MYSQL_PASSWORD: metabase_test

  app:
    image: kurimegane/metabase_test:latest
    container_name: app
    ports:
      - 8080:8080
    links:
      - dbserver
    tty: true
    depends_on:
      - dbserver

  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
      - "3000:3000"
    links:
      - app